In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder,OneHotEncoder
import pickle

In [2]:
# Load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0

In [3]:
# Preprocess the data
# Drop irrelevant features or columns
data=data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9997,709,France,Female,36.0,7,0.00,1,0.0,1.0,42085.58,1
9998,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
9999,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
10000,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0
10001,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0

In [4]:
# Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,Spain,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,France,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,France,0,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,Spain,0,43.0,2,125510.82,1,NaN,1.0,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9997,709,France,0,36.0,7,0.00,1,0.0,1.0,42085.58,1
9998,772,Germany,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1
9999,772,Germany,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1
10000,792,France,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0
10001,792,France,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0

In [5]:
data.isnull().sum()

CreditScore        0
Geography          1
Gender             0
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          1
IsActiveMember     1
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
# data['Geography'].value_counts()
# data['HasCrCard'].value_counts()
data['IsActiveMember'].value_counts()

IsActiveMember
1.0    5150
0.0    4851
Name: count, dtype: int64

In [7]:
data['Age']=data['Age'].fillna(data['Age'].mean())
data['HasCrCard']=data['HasCrCard'].fillna(1.0)
data['IsActiveMember']=data['IsActiveMember'].fillna(1.0)
data['Geography']=data['Geography'].fillna('France')

In [8]:
data.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [9]:
data.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [10]:
# One hot encode geography column
# from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10002 stored elements and shape (10002, 3)>

In [11]:
ndata=pd.get_dummies(data, dtype=int)
ndata

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42.0,2,0.00,1,1.0,1.0,101348.88,1,1,0,0
1,608,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0,0,0,1
2,502,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1,1,0,0
3,699,0,39.0,1,0.00,2,0.0,0.0,93826.63,0,1,0,0
4,850,0,43.0,2,125510.82,1,1.0,1.0,79084.10,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9997,709,0,36.0,7,0.00,1,0.0,1.0,42085.58,1,1,0,0
9998,772,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1,0,1,0
9999,772,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1,0,1,0
10000,792,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0,1,0,0
10001,792,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0,1,0,0

In [12]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [13]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [14]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

       Geography_France  Geography_Germany  Geography_Spain
0                   1.0                0.0              0.0
1                   0.0                0.0              1.0
2                   1.0                0.0              0.0
3                   1.0                0.0              0.0
4                   0.0                0.0              1.0
...                 ...                ...              ...
9997                1.0                0.0              0.0
9998                0.0                1.0              0.0
9999                0.0                1.0              0.0
10000               1.0                0.0              0.0
10001               1.0                0.0              0.0

[10002 rows x 3 columns]

In [15]:
# Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography', axis=1),geo_encoded_df], axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42.0,2,0.00,1,1.0,1.0,101348.88,1,1.0,0.0,0.0
1,608,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0,0.0,0.0,1.0
2,502,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1,1.0,0.0,0.0
3,699,0,39.0,1,0.00,2,0.0,0.0,93826.63,0,1.0,0.0,0.0
4,850,0,43.0,2,125510.82,1,1.0,1.0,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9997,709,0,36.0,7,0.00,1,0.0,1.0,42085.58,1,1.0,0.0,0.0
9998,772,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1,0.0,1.0,0.0
9999,772,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1,0.0,1.0,0.0
10000,792,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0,1.0,0.0,0.0
10001,792,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0,1.0,0.0,0.0

In [16]:
# Save the encoders and scaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender, file)
    
with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [17]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42.0,2,0.00,1,1.0,1.0,101348.88,1,1.0,0.0,0.0
1,608,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0,0.0,0.0,1.0
2,502,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1,1.0,0.0,0.0
3,699,0,39.0,1,0.00,2,0.0,0.0,93826.63,0,1.0,0.0,0.0
4,850,0,43.0,2,125510.82,1,1.0,1.0,79084.10,0,0.0,0.0,1.0

In [18]:
# Divide the dataset into independent and dependent features
X=data.drop('Exited', axis=1)
y=data['Exited']

# Split the data in training and testing sets
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

# Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [19]:
X_train
# X_test

array([[-0.19344335,  0.91360328,  0.29613055, ..., -0.99737876,
         1.72529422, -0.57710974],
       [-0.95045188,  0.91360328, -1.42278638, ..., -0.99737876,
        -0.57961128,  1.73277271],
       [ 0.10728607, -1.094567  , -0.84981407, ...,  1.00262813,
        -0.57961128, -0.57710974],
       ...,
       [ 0.87466458, -1.094567  , -0.08585099, ...,  1.00262813,
        -0.57961128, -0.57710974],
       [ 0.16950595,  0.91360328,  0.39162594, ...,  1.00262813,
        -0.57961128, -0.57710974],
       [ 0.48060534,  0.91360328,  1.15558902, ..., -0.99737876,
         1.72529422, -0.57710974]])

In [20]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler, file)

In [21]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42.0,2,0.00,1,1.0,1.0,101348.88,1,1.0,0.0,0.0
1,608,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0,0.0,0.0,1.0
2,502,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1,1.0,0.0,0.0
3,699,0,39.0,1,0.00,2,0.0,0.0,93826.63,0,1.0,0.0,0.0
4,850,0,43.0,2,125510.82,1,1.0,1.0,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9997,709,0,36.0,7,0.00,1,0.0,1.0,42085.58,1,1.0,0.0,0.0
9998,772,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1,0.0,1.0,0.0
9999,772,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1,0.0,1.0,0.0
10000,792,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0,1.0,0.0,0.0
10001,792,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0,1.0,0.0,0.0

In [22]:
# ANN IMPLEMENTATION

# Importing libraries
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

WARNING:tensorflow:From c:\Users\HP\.conda\envs\newenv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [23]:
# Build our ANN Model
model=Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

WARNING:tensorflow:From c:\Users\HP\.conda\envs\newenv\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [25]:
import tensorflow
# opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [26]:
# compile the model
model.compile(optimizer='adam', loss="binary_crossentropy", metrics=['accuracy'])

WARNING:tensorflow:From c:\Users\HP\.conda\envs\newenv\lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [27]:
# set up the tensorboard
# from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_dir="logs/fit/" +datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [28]:
# Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [29]:
# Train the model
history=model.fit(X_train, y_train, validation_data=(X_test, y_test),epochs=100, callbacks=[tensorflow_callback, early_stopping_callback])

Epoch 1/100
WARNING:tensorflow:From c:\Users\HP\.conda\envs\newenv\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\HP\.conda\envs\newenv\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

251/251 [==============================] - 7s 13ms/step - loss: 0.4517 - accuracy: 0.7993 - val_loss: 0.4023 - val_accuracy: 0.8366
Epoch 2/100
251/251 [==============================] - 3s 12ms/step - loss: 0.3837 - accuracy: 0.8389 - val_loss: 0.3625 - val_accuracy: 0.8541
Epoch 3/100
251/251 [==============================] - 2s 6ms/step - loss: 0.3549 - accuracy: 0.8531 - val_loss: 0.3494 - val_accuracy: 0.8581
Epoch 4/100
251/251 [==============================] - 1s 5ms/step - loss: 0.3452 - accuracy: 0.8594 - val_loss: 0.3468 - val_accuracy: 0.8621
Epoch 5/100
251/251 [==============================] - 1s 5ms/step - loss: 0.3402 - accuracy: 0.8573 - val_loss: 0.3523 - val_accuracy: 0.8611
Epoch 6/100
251/251 [==============================] - 2s 6ms/step - loss: 0.3379 - accuracy: 0.8598 - val_loss: 0.3419 - val_accuracy: 0.8601
Epoch 7/100
251/251 [==============================] - 1s 6ms/step - loss: 0.3321 - accuracy: 0.8640 - val_loss: 0.3474 - val_accuracy: 0.8581
Epoch 8/100
251/251 [==============================] - 2s 8ms/step - loss: 0.3306 - accuracy: 0.8630 - val_loss: 0.3469 - val_accuracy: 0.8636
Epoch 9/100
251/251 [==============================] - 1s 5ms/step - loss: 0.3288 - accuracy: 0.8655 - val_loss: 0.3440 - val_accuracy: 0.8671
Epoch 10/100
251/251 [==============================] - 1s 5ms/step - loss: 0.3256 - accuracy: 0.8655 - val_loss: 0.3416 - val_accuracy: 0.8596
Epoch 11/100
251/251 [==============================] - 2s 6ms/step - loss: 0.3226 - accuracy: 0.8654 - val_loss: 0.3450 - val_accuracy: 0.8621
Epoch 12/100
251/251 [==============================] - 2s 7ms/step - loss: 0.3233 - accuracy: 0.8660 - val_loss: 0.3424 - val_accuracy: 0.8651
Epoch 13/100
251/251 [==============================] - 3s 10ms/step - loss: 0.3197 - accuracy: 0.8680 - val_loss: 0.3398 - val_accuracy: 0.8626
Epoch 14/100
251/251 [==============================] - 4s 14ms/step - loss: 0.3204 - accuracy: 0.8634 - val_loss: 0.3431 - val_accuracy: 0.8621
Epoch 15/100
251/251 [==============================] - 3s 10ms/step - loss: 0.3167 - accuracy: 0.8663 - val_loss: 0.3450 - val_accuracy: 0.8626
Epoch 16/100
251/251 [==============================] - 3s 12ms/step - loss: 0.3147 - accuracy: 0.8689 - val_loss: 0.3474 - val_accuracy: 0.8646
Epoch 17/100
251/251 [==============================] - 3s 12ms/step - loss: 0.3150 - accuracy: 0.8640 - val_loss: 0.3420 - val_accuracy: 0.8641
Epoch 18/100
251/251 [==============================] - 2s 8ms/step - loss: 0.3121 - accuracy: 0.8716 - val_loss: 0.3429 - val_accuracy: 0.8646

In [30]:
# Save the model file
model.save('model.h5')

c:\Users\HP\.conda\envs\newenv\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [31]:
# Load Tensorborad Extension
%load_ext tensorboard

In [32]:
# Load entire tensorboard
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 9392), started 0:48:41 ago. (Use '!kill 9392' to kill it.)