In [1]:
import tensorflow as tf
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
import pickle
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0

In [3]:
# Preprocess the data
data=data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,Spain,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,France,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,France,0,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,Spain,0,43.0,2,125510.82,1,NaN,1.0,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9997,709,France,0,36.0,7,0.00,1,0.0,1.0,42085.58,1
9998,772,Germany,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1
9999,772,Germany,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1
10000,792,France,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0
10001,792,France,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0

In [5]:
data.isnull().sum()

CreditScore        0
Geography          1
Gender             0
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          1
IsActiveMember     1
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
# data['HasCrCard'].value_counts()
#data['IsActiveMember'].value_counts()
data['Geography'].value_counts()

Geography
France     5014
Germany    2510
Spain      2477
Name: count, dtype: int64

In [7]:
data['Age']=data['Age'].fillna(data['Age'].mean())
data['HasCrCard']=data['HasCrCard'].fillna(1)
data['IsActiveMember']=data['IsActiveMember'].fillna(1)
data['Geography']=data['Geography'].fillna("France")

In [8]:
data.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [9]:
# OneHotEncode Geography 
onehot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

       Geography_France  Geography_Germany  Geography_Spain
0                   1.0                0.0              0.0
1                   0.0                0.0              1.0
2                   1.0                0.0              0.0
3                   1.0                0.0              0.0
4                   0.0                0.0              1.0
...                 ...                ...              ...
9997                1.0                0.0              0.0
9998                0.0                1.0              0.0
9999                0.0                1.0              0.0
10000               1.0                0.0              0.0
10001               1.0                0.0              0.0

[10002 rows x 3 columns]

In [10]:
# Combine one_hot encoded columns with the original data
data=pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42.0,2,0.00,1,1.0,1.0,101348.88,1,1.0,0.0,0.0
1,608,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0,0.0,0.0,1.0
2,502,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1,1.0,0.0,0.0
3,699,0,39.0,1,0.00,2,0.0,0.0,93826.63,0,1.0,0.0,0.0
4,850,0,43.0,2,125510.82,1,1.0,1.0,79084.10,0,0.0,0.0,1.0

In [11]:
# Split the data into features and target
X=data.drop('EstimatedSalary', axis=1)
y=data['EstimatedSalary']

In [12]:
# Split the data in training and testing sets
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
# Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [14]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pk1', 'wb')as file:
    pickle.dump(label_encoder_gender, file)
    
with open('onehot_encoder_geo.pk1', 'wb')as file:
    pickle.dump(onehot_encoder_geo, file)
    
with open('scaler.pk1', 'wb')as file:
    pickle.dump(scaler, file)

In [15]:
# ANN IMPLEMENTATION

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [17]:
# Build the model
model=Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

# compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

f:\QSP\Gen AI\deeplearning\DLENV\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir="regressionlogs/fit/" +datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [19]:
##set up Early stopping
early_stopping_callback=EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [20]:
##Train the model 
history=model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[early_stopping_callback,tensorboard_callback]
)

Epoch 1/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 10s 17ms/step - loss: 100529.0391 - mae: 100529.0391 - val_loss: 97966.1719 - val_mae: 97966.1719
Epoch 2/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 99960.5938 - mae: 99960.5938 - val_loss: 96817.3359 - val_mae: 96817.3359
Epoch 3/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 97954.1406 - mae: 97954.1406 - val_loss: 93880.2344 - val_mae: 93880.2344
Epoch 4/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 94004.0000 - mae: 94004.0000 - val_loss: 88937.9766 - val_mae: 88937.9766
Epoch 5/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 88006.8359 - mae: 88006.8359 - val_loss: 82185.4219 - val_mae: 82185.4219
Epoch 6/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 80481.7109 - mae: 80481.7109 - val_loss: 74447.2891 - val_mae: 74447.2891
Epoch 7/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 72461.0391 - mae: 72461.0391 - val_loss: 66789.5859 - val_mae: 66789.5859
Epoch 8/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 64966.0469 - mae: 64966.0469 - val_loss: 60208.8281 - val_mae: 60208.8281
Epoch 9/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 58931.3047 - mae: 58931.3047 - val_loss: 55563.9961 - val_mae: 55563.9961
Epoch 10/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 54853.1719 - mae: 54853.1719 - val_loss: 52901.6602 - val_mae: 52901.6602
Epoch 11/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 52530.7891 - mae: 52530.7891 - val_loss: 51610.8945 - val_mae: 51610.8945
Epoch 12/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 51298.7930 - mae: 51298.7930 - val_loss: 51148.6875 - val_mae: 51148.6875
Epoch 13/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 50780.4922 - mae: 50780.4922 - val_loss: 51016.0547 - val_mae: 51016.0547
Epoch 14/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 50553.4297 - mae: 50553.4297 - val_loss: 50965.4492 - val_mae: 50965.4492
Epoch 15/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 50414.9297 - mae: 50414.9297 - val_loss: 50913.6953 - val_mae: 50913.6953
Epoch 16/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 50334.0273 - mae: 50334.0273 - val_loss: 50870.5000 - val_mae: 50870.5000
Epoch 17/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 50266.7539 - mae: 50266.7539 - val_loss: 50827.3008 - val_mae: 50827.3008
Epoch 18/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 50207.5508 - mae: 50207.5508 - val_loss: 50778.1133 - val_mae: 50778.1133
Epoch 19/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50156.0664 - mae: 50156.0664 - val_loss: 50742.0156 - val_mae: 50742.0156
Epoch 20/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 50108.5430 - mae: 50108.5430 - val_loss: 50702.5352 - val_mae: 50702.5352
Epoch 21/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 50066.6758 - mae: 50066.6758 - val_loss: 50675.9570 - val_mae: 50675.9570
Epoch 22/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 50027.2539 - mae: 50027.2539 - val_loss: 50656.9922 - val_mae: 50656.9922
Epoch 23/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 49988.5781 - mae: 49988.5781 - val_loss: 50625.6211 - val_mae: 50625.6211
Epoch 24/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49957.4023 - mae: 49957.4023 - val_loss: 50603.0195 - val_mae: 50603.0195
Epoch 25/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 49925.0508 - mae: 49925.0508 - val_loss: 50592.6836 - val_mae: 50592.6836
Epoch 26/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49898.5156 - mae: 49898.5156 - val_loss: 50563.7227 - val_mae: 50563.7227
Epoch 27/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 49868.5117 - mae: 49868.5117 - val_loss: 50546.4844 - val_mae: 50546.4844
Epoch 28/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 49847.3945 - mae: 49847.3945 - val_loss: 50527.3906 - val_mae: 50527.3906
Epoch 29/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49824.8711 - mae: 49824.8711 - val_loss: 50509.7070 - val_mae: 50509.7070
Epoch 30/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49805.1445 - mae: 49805.1445 - val_loss: 50510.3750 - val_mae: 50510.3750
Epoch 31/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49784.1211 - mae: 49784.1211 - val_loss: 50499.3711 - val_mae: 50499.3711
Epoch 32/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49762.3711 - mae: 49762.3711 - val_loss: 50482.5703 - val_mae: 50482.5703
Epoch 33/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49744.3711 - mae: 49744.3711 - val_loss: 50475.6719 - val_mae: 50475.6719
Epoch 34/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 49725.5742 - mae: 49725.5742 - val_loss: 50464.6367 - val_mae: 50464.6367
Epoch 35/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49714.9492 - mae: 49714.9492 - val_loss: 50457.3477 - val_mae: 50457.3477
Epoch 36/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49696.2773 - mae: 49696.2773 - val_loss: 50449.1445 - val_mae: 50449.1445
Epoch 37/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49683.1914 - mae: 49683.1914 - val_loss: 50446.0156 - val_mae: 50446.0156
Epoch 38/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 49670.8164 - mae: 49670.8164 - val_loss: 50425.9375 - val_mae: 50425.9375
Epoch 39/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49657.5117 - mae: 49657.5117 - val_loss: 50415.3281 - val_mae: 50415.3281
Epoch 40/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 49645.1406 - mae: 49645.1406 - val_loss: 50388.2266 - val_mae: 50388.2266
Epoch 41/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49631.8359 - mae: 49631.8359 - val_loss: 50380.1367 - val_mae: 50380.1367
Epoch 42/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49620.5703 - mae: 49620.5703 - val_loss: 50368.2500 - val_mae: 50368.2500
Epoch 43/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49611.3398 - mae: 49611.3398 - val_loss: 50362.9844 - val_mae: 50362.9844
Epoch 44/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49600.4375 - mae: 49600.4375 - val_loss: 50358.4023 - val_mae: 50358.4023
Epoch 45/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49590.4102 - mae: 49590.4102 - val_loss: 50370.1250 - val_mae: 50370.1250
Epoch 46/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49582.1953 - mae: 49582.1953 - val_loss: 50352.1562 - val_mae: 50352.1562
Epoch 47/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49574.5000 - mae: 49574.5000 - val_loss: 50341.0586 - val_mae: 50341.0586
Epoch 48/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49561.5703 - mae: 49561.5703 - val_loss: 50361.1016 - val_mae: 50361.1016
Epoch 49/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49552.2695 - mae: 49552.2695 - val_loss: 50349.6914 - val_mae: 50349.6914
Epoch 50/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49544.6133 - mae: 49544.6133 - val_loss: 50347.5664 - val_mae: 50347.5664
Epoch 51/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49538.8867 - mae: 49538.8867 - val_loss: 50356.7148 - val_mae: 50356.7148
Epoch 52/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49529.3477 - mae: 49529.3477 - val_loss: 50333.6211 - val_mae: 50333.6211
Epoch 53/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49520.7695 - mae: 49520.7695 - val_loss: 50346.1562 - val_mae: 50346.1562
Epoch 54/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49514.8594 - mae: 49514.8594 - val_loss: 50334.4297 - val_mae: 50334.4297
Epoch 55/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49506.3516 - mae: 49506.3516 - val_loss: 50330.3242 - val_mae: 50330.3242
Epoch 56/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49500.9258 - mae: 49500.9258 - val_loss: 50325.9336 - val_mae: 50325.9336
Epoch 57/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49494.1289 - mae: 49494.1289 - val_loss: 50321.8555 - val_mae: 50321.8555
Epoch 58/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49488.3086 - mae: 49488.3086 - val_loss: 50347.1094 - val_mae: 50347.1094
Epoch 59/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49482.0898 - mae: 49482.0898 - val_loss: 50348.1211 - val_mae: 50348.1211
Epoch 60/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49475.8672 - mae: 49475.8672 - val_loss: 50344.0703 - val_mae: 50344.0703
Epoch 61/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49465.4336 - mae: 49465.4336 - val_loss: 50350.3203 - val_mae: 50350.3203
Epoch 62/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49464.4609 - mae: 49464.4609 - val_loss: 50347.1133 - val_mae: 50347.1133
Epoch 63/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49456.2422 - mae: 49456.2422 - val_loss: 50349.1055 - val_mae: 50349.1055
Epoch 64/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49449.1211 - mae: 49449.1211 - val_loss: 50344.7539 - val_mae: 50344.7539
Epoch 65/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49443.5273 - mae: 49443.5273 - val_loss: 50335.6328 - val_mae: 50335.6328
Epoch 66/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49441.0312 - mae: 49441.0312 - val_loss: 50337.6914 - val_mae: 50337.6914
Epoch 67/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49432.0938 - mae: 49432.0938 - val_loss: 50301.1875 - val_mae: 50301.1875
Epoch 68/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49429.3711 - mae: 49429.3711 - val_loss: 50307.6562 - val_mae: 50307.6562
Epoch 69/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49423.7188 - mae: 49423.7188 - val_loss: 50334.1641 - val_mae: 50334.1641
Epoch 70/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49419.6836 - mae: 49419.6836 - val_loss: 50317.2031 - val_mae: 50317.2031
Epoch 71/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49418.2852 - mae: 49418.2852 - val_loss: 50322.6719 - val_mae: 50322.6719
Epoch 72/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49410.8906 - mae: 49410.8906 - val_loss: 50339.0469 - val_mae: 50339.0469
Epoch 73/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49408.4102 - mae: 49408.4102 - val_loss: 50332.4531 - val_mae: 50332.4531
Epoch 74/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49400.4883 - mae: 49400.4883 - val_loss: 50317.5039 - val_mae: 50317.5039
Epoch 75/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49398.9648 - mae: 49398.9648 - val_loss: 50304.5078 - val_mae: 50304.5078
Epoch 76/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49393.1094 - mae: 49393.1094 - val_loss: 50294.5508 - val_mae: 50294.5508
Epoch 77/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49389.5703 - mae: 49389.5703 - val_loss: 50317.4766 - val_mae: 50317.4766
Epoch 78/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49388.6680 - mae: 49388.6680 - val_loss: 50325.5391 - val_mae: 50325.5391
Epoch 79/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49383.9258 - mae: 49383.9258 - val_loss: 50314.1328 - val_mae: 50314.1328
Epoch 80/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49380.0195 - mae: 49380.0195 - val_loss: 50316.8086 - val_mae: 50316.8086
Epoch 81/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49374.5000 - mae: 49374.5000 - val_loss: 50331.3008 - val_mae: 50331.3008
Epoch 82/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49375.9648 - mae: 49375.9648 - val_loss: 50321.9766 - val_mae: 50321.9766
Epoch 83/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49368.9961 - mae: 49368.9961 - val_loss: 50313.3242 - val_mae: 50313.3242
Epoch 84/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49364.2773 - mae: 49364.2773 - val_loss: 50319.5820 - val_mae: 50319.5820
Epoch 85/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 49358.8203 - mae: 49358.8203 - val_loss: 50315.1133 - val_mae: 50315.1133
Epoch 86/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 49358.1406 - mae: 49358.1406 - val_loss: 50310.8047 - val_mae: 50310.8047

In [21]:
%load_ext tensorboard

In [22]:
%tensorboard --logdir regressionlogs/fit

In [23]:
#Evaluate model on the test data
test_loss ,test_mae=model.evaluate(X_test,y_test)
print(f"Test mae :{test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 50294.5508 - mae: 50294.5508
Test mae :50294.55078125

In [24]:
model.save("regression_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.